### PR TITLE
Block Claude and Meta AI

### PR DESCRIPTION
**Pull request by pparaxan**
yeh

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
~~feat~~

**Comment by pparaxan** [comment]
> ~feat~

feat these nuts in your mou-

**Comment by a-catgirl-dev** [comment]
> > ~feat~
> 
> feat these nuts in your mou-

Reverted in #2

**Comment by pparaxan** [comment]
> Reverted in #2

Wait wha-

**Pull request merged**
